### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by mxaxel** [mxaxel/unit-testing#1]
Descripcion

Crear codigo base del proyecto

Mockup
....

Pruebas 

- [x] Deberia crear el branch master
- [x] Deberia crear el workflow de CI
- [x] Deberia de proteger el branch master de push directos
- [x] Deberia de proteger master con dos revisores de codigo
- [x] Deberia proteger master a nivel pull request con workflow CI
- [x] Deberia de agregar al repositorio a los ingenieros del equipo de desarrollo 
- [x] Deberia crear el branch develop 
- [x] Deberia de proteger el branch develop de push directos
- [x] Deberia crear el branch release
- [x] Deberia de proteger el branch release de push directos
- [x] Deberia crear el branch hotfixes
- [x] Deberia de proteger el branch hotfixes de push directos

**Comment by sagnnax** [comment]
Closes #1
